version: '2'
services:
  db:
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - data-sync:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: db
  web:
    build: .
    tty: true
    working_dir: ${DEST_PATH}
    volumes:
      - app-sync:${DEST_PATH}:nocopy
    ports:
      - "4000:4000"
    depends_on:
      - db
    container_name: web
volumes:
  app-sync:
    external: true
  data-sync:
    external: true
